- src/app/components/hits/hits.component.ts
- src/app/services/analytics.service.ts
- added capitalized properties
- don't send blank events
> US16360: Analytics Update

- angular.json
- add deploy URL + base href to angular.json
Not super sure this is going to fix anything
> DE6372: Base Href

- src/app/services/search.service.ts
> US16358: Query Params

- src/app/components/hit/hit.component.html
> DE6377: Message Duration

- src/app/app.component.html
- src/app/components/hits/hits.component.html
- src/app/components/hits/hits.component.scss
- src/app/components/hits/hits.component.ts
- src/app/services/search.service.ts
add basic loading functionality instead of pagination
> DE6375: Load More

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/hit-text/hit-text.component.html
- src/app/components/hit-text/hit-text.component.scss
- src/app/components/hit/hit.component.html
- src/app/components/hit/hit.component.scss
- src/app/components/hits/hits.component.html
- src/app/components/tab-filter/tab-filter.component.html
- src/app/components/tab-filter/tab-filter.component.scss
- src/styles.scss
- https://rally1.rallydev.com/#/41662702253d/detail/defect/285991175480/tasks
> DE6384: Make Designs Look More Good

- src/app/components/hit/hit.component.scss
- src/app/components/tab-filter/tab-filter.component.scss
- src/styles.scss
- remove header jank
- widen spaces between tabs
- fix width img and meta data within result component
> DE6384: More Design Things

- src/app/components/search-input/search-input.component.html
- src/index.html
> US16467: Autofocus

- .travis.yml
- Trying to get Travis to talk with Slack
> [CYP] Slack integration

- angular.json
- package.json
- yarn.lock
> DE6444: Broken Header Images

- src/app/components/hits/hits.component.ts
Now that we have routing, I am adding in a tracking event that fires when someone shares a URL with search params. It's the exact same track we use when someone actually searches but this one will work when you hit a URL with query params.
@s-henney 🤞 this is the last PR
> US16397: Conversion Event

- src/app/components/hit-widget/hit-widget.component.html
- src/app/components/hit-widget/hit-widget.component.scss
Altering some of the logic to support the styled, image based widget as well as plain ol' HTMLz
> DEXXXX: Widget Types

- src/app/components/hit/hit.component.html
- src/app/components/hit/hit.component.ts
🙈 **Warning: Disgusting Code Ahead** 🙈
> US16684: Album Art

- cypress/integration/APIOnly/results_with_composit_links_spec.js
- cypress/integration/searchPage/no_results_spec.js
- cypress/integration/searchPage/pre_search_content_spec.js
- cypress/integration/searchPage/result_navigation_spec.js
- cypress/integration/searchPage/search_params_in_url_spec.js
- Added tests for URL search parameters
- Moved tests to folders
> [CYP] - URL parameter tests

- .travis.yml
- cypress.json
- cypress/Algolia/AlgoliaApi.js
- cypress/Algolia/AlgoliaResultManager.js
- cypress/Contentful/Models/MessageModel.js
- cypress/integration/result_navigation_spec.js
- cypress/integration/results_with_composit_links_spec.js
- cypress/kickOffCypress.sh
- Forgot to pass the media url to Travis
- Restructured tests a bit to make better use of promises (thanks @j-brammer)
- Fixed bug in another test where clicking a result was not possible because of its location on the page
> [CYP] - Message url test fix

- src/app/components/hits/hits.component.html
- src/app/components/hits/hits.component.ts
- src/app/services/analytics.service.ts
Conversion tracking wasn't working properly because of the way I was matching the element you clicked on with the algolia index. I now use the objectID (which is unique) to do this.
> DE6523: Fix Analytics

- src/app/components/embeddable/search-modal/search-modal.component.html
- src/app/components/embeddable/search-modal/search-modal.component.scss
- src/app/components/tab-filter/tab-filter.component.scss
- overflow scroll
- SVG icon colors
- filter tabs
> DE6550: Embed UI

- src/app/components/embeddable/search-modal/search-modal.component.scss
> DE6550: Modal UI

- cypress/integration/searchOverlay/result_card_format_spec.js
- cypress/kickOffCypress.sh
- cypress/support/SearchPanel.js
- Fixed media url value beings sent to TravisCI
- Fixed a logic problem where the previous filter was still applied to a new keyword, but the keyword didn't have that filter available, so no results were displayed.
> [CYP] DE6768 - Config and logic fix

- .travis.yml
- Run Cypress in parallel on 5 machines
> [CYP] US17265 - Run Cypress in parallel

- netlify.toml
- package.json
- src/index.html
- src/styles.scss
- yarn.lock
Add header, footer, and snail trail. Also add sed script to replace environment.
> US17689 - New Shared Header

- angular.json
- cypress/integration/searchOverlayCompatible/result_card_format_spec.js
- yarn.lock
- Updated some search keywords so results have all components in the layout we want to test
> [CYP] US18016 - Update search queries

- src/app/components/tab-filter/tab-filter.component.html
- src/app/components/tab-filter/tab-filter.component.ts
Strip underscores from search facets
> DE7336 Search Facets

- src/app/components/tab-filter/tab-filter.component.html
- src/app/components/tab-filter/tab-filter.component.ts
Strip underscores from search facets
> Development to master

- cypress/integration/APIOnly/algolia_response_properties_spec.js
- cypress/integration/searchOverlayCompatible/result_navigation_spec.js
- cypress/integration/searchPage/analytics_events_spec.js
- cypress/integration/searchPage/url_search_params_spec.js
- cypress/support/commands.js
error handling for uncaught exception error
> Us19353 update crds search test

- cypress/integration/APIOnly/algolia_response_properties_spec.js
- cypress/integration/searchOverlayCompatible/result_navigation_spec.js
updated standard properties and  content types
> updated standard properties and  content types
